### ISSUE TITLE
Udemy Says : 403 Forbidden retry after few minutes

### ISSUE THREAD

**Issue by AnthonyIp** [r0oth3x49/udemy-dl#298]
Hi! 

just as the title mention, i have an error when i try to download course.
"Udemy Says : 403 Forbidden retry after few minutes" Does anyone has the same error ?

**Comment by r0oth3x49** [comment]
@AnthonyIp this is the updated version please read the msg carefully, what it stats, you should wait atleast 2 to 3 minute before moving toward new download.

**Comment by AnthonyIp** [comment]
No, I didn't even start to download yet and I got this warning.
I would understand if I had to wait if I had finished to download a course but I haven't.

**Comment by r0oth3x49** [comment]
@AnthonyIp then you should upgrade `pyOpenSSL`, `requests`, `requests[security]`. for me it works fine i cannot reproduce

**Comment by satyaaditech** [comment]
I've  upgrade each one you havve mention above, but when I entered user and pass, It keep saying "Udemy Says:403 Forbiden retry a few minutes...", as matter fact I have'nt donwload anything yet....Do you have solution to this problem? cause a few days a go averything seems to be OK. Thnk you

**Comment by satyaaditech** [comment]
> Hi!
> 
> just as the title mention, i have an error when i try to download course.
> "Udemy Says : 403 Forbidden retry after few minutes" Does anyone has the same error ?

Yes, I do have same problem .....

**Comment by alexgiggi** [comment]
Same problem here.. :-(

**Comment by ThabisoMagwaza** [comment]
Same problem here...

**Comment by dwaynepaschall** [comment]
Seems like a new issue has popped up recently as I can replicate this error independently. Do you have version numbers for the above listed libs in a working environment? I've updated all of the relevant libs above and still have the same error. With known-good-config versions maybe we can help track it down?

**Comment by mkindika** [comment]
Same problem here...

**Comment by NikhilPampatwar** [comment]
Same problem... with Python 2.75 and latest udemy-dl (installed today using requirements.txt)

![image](https://user-images.githubusercontent.com/10534412/48958682-afc6c500-ef58-11e8-8c9c-23501d8af831.png)

**Comment by jessequinn** [comment]
any solution yet?

**Comment by dwaynepaschall** [comment]
None that I’ve seen

**Comment by tOlorun** [comment]
Any workaround?

**Comment by dwaynepaschall** [comment]
Did you use the system Python that ships with MacOs (python 2.7) or an
updated version (e.g., Python 3.6.6 with conda)?

**Comment by satyaaditech** [comment]
> Any workaround?

I Just make simple tutorial how to download using python 3.7, I hope It will do the work.......https://youtu.be/o6FkYUWGqYs

**Comment by r0oth3x49** [comment]
the issue is fixed guys, simply pull the latest master and enjoy learning sorry for not seeing the issue for long.

**Comment by Liquid09** [comment]
Thx its work !! Nice Job

**Comment by SriramStark** [comment]
how to fix that

**Comment by SriramStark** [comment]
I have used the cookie method and then it starts showing 403 error

**Comment by arun578** [comment]
Still getting the same error: Udemy Says : 403 Forbidden You should use cookie base method to authenticate or try again in few minutes ...
Please provide some solution.
Thanks in advance.
